export enum CustomerEvent {
    CUSTOMER_GET_ALL = "[Customer-Api] GET ALL CUSTOMERS EVENT",
    CUSTOMER_CREATE = "[Customer-Api] CUSTOMER CREATE EVENT",
    REFRESH = "REFRESH LIST DATA EVENT",
    CUSTOMER_STATE_SWITCH = "[Customer-Api] SWITCH CUSTOMER STATE EVENT",
    CUSTOMER_UPDATE = "[Customer-Api] UPDATE CUSTOMER EVENT"
}
export enum BankAccountEvent {
    BANK_ACCOUNT_GET_ALL ="[Bank-Account-Api] GET ALL BANK ACCOUNTS EVENT",
    BANK_ACCOUNT_CREATE = "[Bank-Account-Api] CREATE A NEW BANK ACCOUNT EVENT",
    REFRESH = "REFRESH TABLE DATA EVENT",
    BANK_ACCOUNT_OPERATION_CREATE = "[Bank-Account-Api] CREATE NEW OPERATION ON BANK ACCOUNT EVENT",
    BANK_ACCOUNT_SWITCH_STATE = "[Bank-Account-Api] SWITCH BANK ACCOUNT STATE EVENT",
    BANK_ACCOUNT_CHANGE_OVERDRAFT = "[Bank-Account-Api] CHANGE BANK ACCOUNT OVERDRAFT EVENT",
    BANK_ACCOUNT_CHANGE_INTEREST_RATE = "[Bank-Account-Api] CHANGE BANK ACCOUNT INTEREST RATE EVENT",
    BANK_ACCOUNT_TRANSFER_OPERATION = "[Bank-Account-Api] TRANSFER OPERATION BETWEEN BANK ACCOUNTS EVENT "
}

export enum OperationEvent {
    OPERATION_GET_ALL = "[Operation-Api] GET ALL OPERATIONS EVENT",
    OPERATION_CREATE_NEW = "[Operation-Api] CREATE NEW OPERATION EVENT"
}

export enum UserEvent {
    LOGIN = "[User] LOGIN EVENT EVENT",
    REGISTER = "[User] REGISTER USER EVENT EVENT",
    ROLE_CREATE = "[Role] CREATE NEW ROLE EVENT",
    REFRESH = "[User] REFRESH LIST OF USERS EVENT",
    ADD_ROLE_BUTTON_CLICKED="ADD ROLE BUTTON HAS BEEN CLICKED EVENT",
    REMOVE_ROLE_BUTTON_CLICKED = "REMOVE ROLE BUTTON HAS BEEN CLICKED EVENT",
    USER_ROLE_ADD = "[Use] ADD NEW ROLE TO USER EVENT",
    USER_ROLE_REMOVE = "[User ] REMOVE ROLE FROM USER EVENT",
    USER_DELETE = "[User] DELETE USER EVENT",
    USER_EDIT = "[User] Edit USER INFO EVENT"
}