apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  labels:
    app: kafka-ui
  namespace: exalt-bank-account-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      name: kafka-ui
      labels:
        app: kafka-ui
    spec:
      serviceAccountName: exalt-bank-account-app-sa
      initContainers:
        - name: kafka1-busybox
          image: busybox
          command:
            - 'sh'
            - '-c'
            - 'until nc -z kafka-server1 9092; do echo waiting for kafka-server1 ready; sleep 5; done;'
        - name: kafka2-busybox
          image: busybox
          command:
            - 'sh'
            - '-c'
            - 'until nc -z kafka-server2 9093; do echo waiting for kafka-server2 ready; sleep 5; done;'
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
              name: kafka-ui-port
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              valueFrom:
                configMapKeyRef:
                  name: exalt-bank-account-app-env-var-cm
                  key: kafka_cluster_1_key
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              valueFrom:
                configMapKeyRef:
                  key: kafka_servers_key
                  name: exalt-bank-account-app-env-var-cm
            - name: KAFKA_CLUSTERS_0_METRICS_PORT
              valueFrom:
                configMapKeyRef:
                  key: kafka-cluster_metric_port_1_key
                  name: exalt-bank-account-app-env-var-cm
            - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
              valueFrom:
                configMapKeyRef:
                  key: kafka_cluster_schema_registry_key
                  name: exalt-bank-account-app-env-var-cm
            - name: KAFKA_CLUSTERS_1_NAME
              valueFrom:
                configMapKeyRef:
                  name: exalt-bank-account-app-env-var-cm
                  key: kafka_cluster_2_key
            - name: KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS
              valueFrom:
                configMapKeyRef:
                  key: kafka_servers_key
                  name: exalt-bank-account-app-env-var-cm
            - name: KAFKA_CLUSTERS_1_METRICS_PORT
              valueFrom:
                configMapKeyRef:
                  key: kafka-cluster_metric_port_2_key
                  name: exalt-bank-account-app-env-var-cm
            - name: KAFKA_CLUSTERS_1_SCHEMAREGISTRY
              valueFrom:
                configMapKeyRef:
                  key: kafka_cluster_schema_registry_key
                  name: exalt-bank-account-app-env-var-cm
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  labels:
    app: kafka-ui
  namespace: exalt-bank-account-app-ns
spec:
  selector:
    app: kafka-ui
  ports:
    - port: 8080
      protocol: TCP
      targetPort: kafka-ui-port
      name: kfk-ui-port-svc
  type: ClusterIP