# persistence volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-persistent-volume
  labels:
    app: db-persistent-volume
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/var/lib/mysql"
---
# persistence volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-persistent-volume-claim
  labels:
    app: db-persistent-volume-claim
  namespace: exalt-bank-account-app-ns
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 500M
---
# database pwd
apiVersion: v1
kind: Secret
metadata:
  namespace: exalt-bank-account-app-ns
  name: db-credentials
  labels:
    app: db-credentials
type: Opaque
data:
  mysql-mdp: "cm9vdA=="
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-account-app-apis-dbs
  labels:
    app: bank-account-app-apis-dbs
  namespace: exalt-bank-account-app-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-account-app-apis-dbs
  template:
    metadata:
      name: bank-account-app-apis-dbs
      labels:
        app: bank-account-app-apis-dbs
    spec:
      serviceAccountName: exalt-bank-account-app-sa
      containers:
        - name: bank-account-app-apis-dbs
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
              name: db-host-port
          startupProbe:
            tcpSocket:
              port: db-host-port
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: db-host-port
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: db-host-port
            initialDelaySeconds: 30
            periodSeconds: 15
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: mysql-mdp
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-persistent-volume-claim
      restartPolicy: Always

---
# database service
apiVersion: v1
kind: Service
metadata:
  name: bank-account-app-apis-dbs
  labels:
    app: bank-account-app-apis-dbs
  namespace: exalt-bank-account-app-ns
spec:
  selector:
    app: bank-account-app-apis-dbs
  ports:
    - port: 3306
      protocol: TCP
      targetPort: db-host-port
      name: db-host-port-svc
  type: ClusterIP