# kafka servers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-server
  labels:
    app: kafka-server
  namespace: exalt-bank-account-app-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-server
  template:
    metadata:
      name: kafka-server
      labels:
        app: kafka-server
    spec:
      serviceAccountName: exalt-bank-account-app-sa
      initContainers:
        - name: zookeeper-busybox
          image: busybox
          command:
            - 'sh'
            - '-c'
            - 'until nc -z zookeeper-server 2181; do echo waiting for zookeeper-server ready; sleep 5; done;'
      containers:
        - name: kafka-server
          image: obsidiandynamics/kafka
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
              protocol: TCP
              name: kafka-port
          env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef:
                  key: kafka_broker_id_key
                  name: exalt-config-map-variables
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  key: zookeeper_connect_key
                  name: exalt-config-map-variables
            - name: ALLOW_PLAINTEXT_LISTENER
              valueFrom:
                configMapKeyRef:
                  key: allowing_plain_text_lister_key
                  name: exalt-config-map-variables
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              valueFrom:
                configMapKeyRef:
                  key: kafka_listeners_security_protocol_map_key
                  name: exalt-config-map-variables
            - name: KAFKA_LISTENERS
              valueFrom:
                configMapKeyRef:
                  key: kafka_listeners_key
                  name: exalt-config-map-variables
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  key: kafka_advertised_listeners_keys
                  name: exalt-config-map-variables
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-server
  labels:
    app: kafka-server
  namespace: exalt-bank-account-app-ns
spec:
  selector:
    app: kafka-server
  ports:
    - port: 9092
      protocol: TCP
      targetPort: kafka-port
      name: kafka-port-svc
  type: ClusterIP