apiVersion: apps/v1
kind: Deployment
metadata:
  name: exalt-business-microservice-operation
  labels:
    app: exalt-business-microservice-operation
  namespace: exalt-bank-account-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exalt-business-microservice-operation
  template:
    metadata:
      name: exalt-business-microservice-operation
      labels:
        app: exalt-business-microservice-operation
    spec:
      serviceAccountName: exalt-bank-account-app-sa
      initContainers:
        - name: ms-config-busybox
          image: busybox
          command:
            - 'sh'
            - '-c'
            - 'until nc -z exalt-microservices-configuration-server 8100; do echo waiting for mss-config-service to be ready; sleep 5; done;'
        - name: database-busybox
          image: busybox
          command:
            - 'sh'
            - '-c'
            - 'until nc -z bank-account-app-apis-dbs 3306; do echo waiting for database to be ready; sleep 5; done;'
      containers:
        - name: exalt-business-microservice-operation
          image: placidenduwayo1/exalt-business-microservice-operation:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8105
              name: operation-api
          env:
            - name: APPLICATION_NAME7
              valueFrom:
                configMapKeyRef:
                  key: application_name7
                  name: exalt-bank-account-app-cm
            -
          livenessProbe:
            tcpSocket:
              port: operation-api
            initialDelaySeconds: 50
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: operation-api
            initialDelaySeconds: 50
            periodSeconds: 30

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: exalt-business-microservice-operation
  labels:
    app: exalt-business-microservice-operation
  namespace: exalt-bank-account-app-ns
spec:
  selector:
    app: exalt-business-microservice-operation
  ports:
    - protocol: TCP
      port: 8105
      targetPort: operation-api
      name: operation-port
  type: ClusterIP
      