/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OriginAccountAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8538501401640885718L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OriginAccountAvro\",\"namespace\":\"fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer\",\"fields\":[{\"name\":\"accountId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"state\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"balance\",\"type\":\"double\"},{\"name\":\"customerId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"originCustomer\",\"type\":{\"type\":\"record\",\"name\":\"OriginCustomerAvro\",\"fields\":[{\"name\":\"customerId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"firstname\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"lastname\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"state\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"email\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OriginAccountAvro> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OriginAccountAvro> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OriginAccountAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OriginAccountAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OriginAccountAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OriginAccountAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OriginAccountAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OriginAccountAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OriginAccountAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String accountId;
  private java.lang.String type;
  private java.lang.String state;
  private double balance;
  private java.lang.String customerId;
  private fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginCustomerAvro originCustomer;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OriginAccountAvro() {}

  /**
   * All-args constructor.
   * @param accountId The new value for accountId
   * @param type The new value for type
   * @param state The new value for state
   * @param balance The new value for balance
   * @param customerId The new value for customerId
   * @param originCustomer The new value for originCustomer
   */
  public OriginAccountAvro(java.lang.String accountId, java.lang.String type, java.lang.String state, java.lang.Double balance, java.lang.String customerId, fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginCustomerAvro originCustomer) {
    this.accountId = accountId;
    this.type = type;
    this.state = state;
    this.balance = balance;
    this.customerId = customerId;
    this.originCustomer = originCustomer;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return accountId;
    case 1: return type;
    case 2: return state;
    case 3: return balance;
    case 4: return customerId;
    case 5: return originCustomer;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: accountId = value$ != null ? value$.toString() : null; break;
    case 1: type = value$ != null ? value$.toString() : null; break;
    case 2: state = value$ != null ? value$.toString() : null; break;
    case 3: balance = (java.lang.Double)value$; break;
    case 4: customerId = value$ != null ? value$.toString() : null; break;
    case 5: originCustomer = (fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginCustomerAvro)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'accountId' field.
   * @return The value of the 'accountId' field.
   */
  public java.lang.String getAccountId() {
    return accountId;
  }


  /**
   * Sets the value of the 'accountId' field.
   * @param value the value to set.
   */
  public void setAccountId(java.lang.String value) {
    this.accountId = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.String getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.String value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'state' field.
   * @return The value of the 'state' field.
   */
  public java.lang.String getState() {
    return state;
  }


  /**
   * Sets the value of the 'state' field.
   * @param value the value to set.
   */
  public void setState(java.lang.String value) {
    this.state = value;
  }

  /**
   * Gets the value of the 'balance' field.
   * @return The value of the 'balance' field.
   */
  public double getBalance() {
    return balance;
  }


  /**
   * Sets the value of the 'balance' field.
   * @param value the value to set.
   */
  public void setBalance(double value) {
    this.balance = value;
  }

  /**
   * Gets the value of the 'customerId' field.
   * @return The value of the 'customerId' field.
   */
  public java.lang.String getCustomerId() {
    return customerId;
  }


  /**
   * Sets the value of the 'customerId' field.
   * @param value the value to set.
   */
  public void setCustomerId(java.lang.String value) {
    this.customerId = value;
  }

  /**
   * Gets the value of the 'originCustomer' field.
   * @return The value of the 'originCustomer' field.
   */
  public fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginCustomerAvro getOriginCustomer() {
    return originCustomer;
  }


  /**
   * Sets the value of the 'originCustomer' field.
   * @param value the value to set.
   */
  public void setOriginCustomer(fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginCustomerAvro value) {
    this.originCustomer = value;
  }

  /**
   * Creates a new OriginAccountAvro RecordBuilder.
   * @return A new OriginAccountAvro RecordBuilder
   */
  public static fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder newBuilder() {
    return new fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder();
  }

  /**
   * Creates a new OriginAccountAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OriginAccountAvro RecordBuilder
   */
  public static fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder newBuilder(fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder other) {
    if (other == null) {
      return new fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder();
    } else {
      return new fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder(other);
    }
  }

  /**
   * Creates a new OriginAccountAvro RecordBuilder by copying an existing OriginAccountAvro instance.
   * @param other The existing instance to copy.
   * @return A new OriginAccountAvro RecordBuilder
   */
  public static fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder newBuilder(fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro other) {
    if (other == null) {
      return new fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder();
    } else {
      return new fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for OriginAccountAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OriginAccountAvro>
    implements org.apache.avro.data.RecordBuilder<OriginAccountAvro> {

    private java.lang.String accountId;
    private java.lang.String type;
    private java.lang.String state;
    private double balance;
    private java.lang.String customerId;
    private fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginCustomerAvro originCustomer;
    private fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginCustomerAvro.Builder originCustomerBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.accountId)) {
        this.accountId = data().deepCopy(fields()[0].schema(), other.accountId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.state)) {
        this.state = data().deepCopy(fields()[2].schema(), other.state);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.balance)) {
        this.balance = data().deepCopy(fields()[3].schema(), other.balance);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.customerId)) {
        this.customerId = data().deepCopy(fields()[4].schema(), other.customerId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.originCustomer)) {
        this.originCustomer = data().deepCopy(fields()[5].schema(), other.originCustomer);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (other.hasOriginCustomerBuilder()) {
        this.originCustomerBuilder = fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginCustomerAvro.newBuilder(other.getOriginCustomerBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing OriginAccountAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.accountId)) {
        this.accountId = data().deepCopy(fields()[0].schema(), other.accountId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.state)) {
        this.state = data().deepCopy(fields()[2].schema(), other.state);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.balance)) {
        this.balance = data().deepCopy(fields()[3].schema(), other.balance);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.customerId)) {
        this.customerId = data().deepCopy(fields()[4].schema(), other.customerId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.originCustomer)) {
        this.originCustomer = data().deepCopy(fields()[5].schema(), other.originCustomer);
        fieldSetFlags()[5] = true;
      }
      this.originCustomerBuilder = null;
    }

    /**
      * Gets the value of the 'accountId' field.
      * @return The value.
      */
    public java.lang.String getAccountId() {
      return accountId;
    }


    /**
      * Sets the value of the 'accountId' field.
      * @param value The value of 'accountId'.
      * @return This builder.
      */
    public fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder setAccountId(java.lang.String value) {
      validate(fields()[0], value);
      this.accountId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'accountId' field has been set.
      * @return True if the 'accountId' field has been set, false otherwise.
      */
    public boolean hasAccountId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'accountId' field.
      * @return This builder.
      */
    public fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder clearAccountId() {
      accountId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.String getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder setType(java.lang.String value) {
      validate(fields()[1], value);
      this.type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder clearType() {
      type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'state' field.
      * @return The value.
      */
    public java.lang.String getState() {
      return state;
    }


    /**
      * Sets the value of the 'state' field.
      * @param value The value of 'state'.
      * @return This builder.
      */
    public fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder setState(java.lang.String value) {
      validate(fields()[2], value);
      this.state = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'state' field has been set.
      * @return True if the 'state' field has been set, false otherwise.
      */
    public boolean hasState() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'state' field.
      * @return This builder.
      */
    public fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder clearState() {
      state = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'balance' field.
      * @return The value.
      */
    public double getBalance() {
      return balance;
    }


    /**
      * Sets the value of the 'balance' field.
      * @param value The value of 'balance'.
      * @return This builder.
      */
    public fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder setBalance(double value) {
      validate(fields()[3], value);
      this.balance = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'balance' field has been set.
      * @return True if the 'balance' field has been set, false otherwise.
      */
    public boolean hasBalance() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'balance' field.
      * @return This builder.
      */
    public fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder clearBalance() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerId' field.
      * @return The value.
      */
    public java.lang.String getCustomerId() {
      return customerId;
    }


    /**
      * Sets the value of the 'customerId' field.
      * @param value The value of 'customerId'.
      * @return This builder.
      */
    public fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder setCustomerId(java.lang.String value) {
      validate(fields()[4], value);
      this.customerId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'customerId' field has been set.
      * @return True if the 'customerId' field has been set, false otherwise.
      */
    public boolean hasCustomerId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'customerId' field.
      * @return This builder.
      */
    public fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder clearCustomerId() {
      customerId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'originCustomer' field.
      * @return The value.
      */
    public fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginCustomerAvro getOriginCustomer() {
      return originCustomer;
    }


    /**
      * Sets the value of the 'originCustomer' field.
      * @param value The value of 'originCustomer'.
      * @return This builder.
      */
    public fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder setOriginCustomer(fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginCustomerAvro value) {
      validate(fields()[5], value);
      this.originCustomerBuilder = null;
      this.originCustomer = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'originCustomer' field has been set.
      * @return True if the 'originCustomer' field has been set, false otherwise.
      */
    public boolean hasOriginCustomer() {
      return fieldSetFlags()[5];
    }

    /**
     * Gets the Builder instance for the 'originCustomer' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginCustomerAvro.Builder getOriginCustomerBuilder() {
      if (originCustomerBuilder == null) {
        if (hasOriginCustomer()) {
          setOriginCustomerBuilder(fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginCustomerAvro.newBuilder(originCustomer));
        } else {
          setOriginCustomerBuilder(fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginCustomerAvro.newBuilder());
        }
      }
      return originCustomerBuilder;
    }

    /**
     * Sets the Builder instance for the 'originCustomer' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder setOriginCustomerBuilder(fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginCustomerAvro.Builder value) {
      clearOriginCustomer();
      originCustomerBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'originCustomer' field has an active Builder instance
     * @return True if the 'originCustomer' field has an active Builder instance
     */
    public boolean hasOriginCustomerBuilder() {
      return originCustomerBuilder != null;
    }

    /**
      * Clears the value of the 'originCustomer' field.
      * @return This builder.
      */
    public fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginAccountAvro.Builder clearOriginCustomer() {
      originCustomer = null;
      originCustomerBuilder = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OriginAccountAvro build() {
      try {
        OriginAccountAvro record = new OriginAccountAvro();
        record.accountId = fieldSetFlags()[0] ? this.accountId : (java.lang.String) defaultValue(fields()[0]);
        record.type = fieldSetFlags()[1] ? this.type : (java.lang.String) defaultValue(fields()[1]);
        record.state = fieldSetFlags()[2] ? this.state : (java.lang.String) defaultValue(fields()[2]);
        record.balance = fieldSetFlags()[3] ? this.balance : (java.lang.Double) defaultValue(fields()[3]);
        record.customerId = fieldSetFlags()[4] ? this.customerId : (java.lang.String) defaultValue(fields()[4]);
        if (originCustomerBuilder != null) {
          try {
            record.originCustomer = this.originCustomerBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("originCustomer"));
            throw e;
          }
        } else {
          record.originCustomer = fieldSetFlags()[5] ? this.originCustomer : (fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginCustomerAvro) defaultValue(fields()[5]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OriginAccountAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<OriginAccountAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OriginAccountAvro>
    READER$ = (org.apache.avro.io.DatumReader<OriginAccountAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.accountId);

    out.writeString(this.type);

    out.writeString(this.state);

    out.writeDouble(this.balance);

    out.writeString(this.customerId);

    this.originCustomer.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.accountId = in.readString();

      this.type = in.readString();

      this.state = in.readString();

      this.balance = in.readDouble();

      this.customerId = in.readString();

      if (this.originCustomer == null) {
        this.originCustomer = new fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginCustomerAvro();
      }
      this.originCustomer.customDecode(in);

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.accountId = in.readString();
          break;

        case 1:
          this.type = in.readString();
          break;

        case 2:
          this.state = in.readString();
          break;

        case 3:
          this.balance = in.readDouble();
          break;

        case 4:
          this.customerId = in.readString();
          break;

        case 5:
          if (this.originCustomer == null) {
            this.originCustomer = new fr.exalt.businessmicroserviceoperation.domain.avromodels.transfer.OriginCustomerAvro();
          }
          this.originCustomer.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










