apiVersion: apps/v1
kind: Deployment
metadata:
  name: exalt-microservices-configuration-server
  labels:
    app: exalt-microservices-configuration-server
  namespace: exalt-bank-account-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exalt-microservices-configuration-server
  template:
    metadata:
      name: exalt-microservices-configuration-server
      labels:
        app: exalt-microservices-configuration-server
    spec:
      serviceAccountName: exalt-bank-account-app-sa
      containers:
        - name: exalt-microservices-configuration-server
          image: placidenduwayo1/exalt-microservices-configuration-server:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8100
              name: ms-config-svc
          env:
            - name: APPLICATION_NAME1
              valueFrom:
                configMapKeyRef:
                  key: application_name1
                  name: exalt-bank-account-app-env-var-cm
            - name: SERVER_PORT1
              valueFrom:
                configMapKeyRef:
                  key: server_port1
                  name: exalt-bank-account-app-env-var-cm
            - name: CLOUD_CONFIG_SERVER_GIT_URI
              valueFrom:
                secretKeyRef:
                  key: cloud_config_server_git_uri
                  name: exalt-bank-account-app-credentials
            - name: CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL
              valueFrom:
                secretKeyRef:
                  key: cloud_config_server_git_default_label
                  name: exalt-bank-account-app-credentials
            - name: CLOUD_CONFIG_SERVER_GIT_PATHS
              valueFrom:
                secretKeyRef:
                  key: cloud_config_server_git_paths
                  name: exalt-bank-account-app-credentials
            - name: CLOUD_CONFIG_SERVER_GIT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: cloud_config_server_git_username
                  name: exalt-bank-account-app-credentials
            - name: CLOUD_CONFIG_SERVER_GIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: cloud_config_server_git_password
                  name: exalt-bank-account-app-credentials
          livenessProbe:
            httpGet:
              port: ms-config-svc
              path: /actuator/health/liveness
            initialDelaySeconds: 50
            periodSeconds: 30
          readinessProbe:
            httpGet:
              port: ms-config-svc
              path: /actuator/health/readiness
            initialDelaySeconds: 50
            periodSeconds: 30
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: exalt-microservices-configuration-server
  labels:
    app: exalt-microservices-configuration-server
  namespace: exalt-bank-account-app-ns
spec:
  selector:
    app: exalt-microservices-configuration-server
  ports:
    - port: 8100
      protocol: TCP
      targetPort: ms-config-svc
      name: ms-config-port
  type: ClusterIP